# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IFevluuTgRXmaGoUwXuuKGqwvc-G5xRE
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import io
  
df = pd.read_csv(io.BytesIO(uploaded['train.csv'])) 
triplet_dataset = pd.read_csv('train.csv',nrows = 10000, sep = ',', names = ['user','song','play_count'], header=1)

output_dict = {}
with open('train.csv') as f:
    for line_number,line in enumerate(f):
        user = line.split(',')[0]
        play_count = int(line.split(',')[2])
        if user in output_dict:
            play_count += output_dict[user]
            output_dict.update({user:play_count})
        output_dict.update({user:play_count})
        

output_list = [{'user': k, 'play_count':v} for k,v in output_dict.items()]
play_count_df = pd.DataFrame(output_list)

print (df)

print (play_count_df)

output_dict1 = {}
with open('train.csv') as f:
    for line_number,line in enumerate(f):
        song = line.split(',')[1]
        play_count = int(line.split(',')[2])
        if song in output_dict1:
            play_count += output_dict1[song]
            output_dict1.update({song:play_count})
        output_dict1.update({song:play_count})
        

output_list1 = [{'song': k, 'play_count':v} for k,v in output_dict1.items()]
play_song_count_df = pd.DataFrame(output_list1)

print(play_song_count_df)

topuser_song_df= play_count_df.sort_values(by='play_count')
print (topuser_song_df)

topsong_play_df= play_song_count_df.sort_values(by='play_count')
print (topsong_play_df)